version: "3.9"

services:
  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - mynetwork
    command: >
      sh -c "
        ollama serve &
        sleep 5 &&
        curl -X POST http://localhost:11434/api/generate -H 'Content-Type: application/json' -d '{\"model\":\"llama3\",\"prompt\":\"Ready\"}' || true &&
        wait
      "

  backend:
    build:
      context: ./server
    # IMPORTANT: remove ports mapping, it's ignored in host mode
    network_mode: host
    env_file:
      - "./server/.env"
    depends_on:
      ollama:
        condition: service_started

volumes:
  ollama_models:

networks:
  mynetwork:

