version: "3.9"

services:
  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=0
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - mynetwork
    command: >
      sh -c "
        ollama serve &
        sleep 5 &&
        curl -X POST http://0.0.0.0:11434/api/generate \
          -H 'Content-Type: application/json' \
          -d '{\"model\":\"llama3\",\"prompt\":\"Ready\"}' || true &&
        wait
      "

  backend:
    ports:
      - "8080:8080"
    build:
      context: ./server
    env_file:
      - "./server/.env"
    depends_on:
      ollama:
        condition: service_started
    networks:
      - mynetwork

volumes:
  ollama_models:

networks:
  mynetwork:
