version: "3.9"

services:
  neo4j:
    image: neo4j:2025.06.0-enterprise
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "eval"
      NEO4J_AUTH: "neo4j/testpassword"
      NEO4J_dbms_default__database: "neo4j"
    ports:
      - "7687:7687" # Bolt protocol (backend connects here)
      - "7474:7474" # Neo4j browser UI
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: >
        sh -c "cypher-shell -u neo4j -p $NEO4J_PASS 'RETURN 1'"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - mynetwork
    command: >
      sh -c "
        ollama serve &
        sleep 5 &&
        curl -X POST http://localhost:11434/api/generate -H 'Content-Type: application/json' -d '{\"model\":\"llama3\",\"prompt\":\"Ready\"}' || true &&
        wait
      "
    # If we want to limit RAM usage:
    # deploy:
    #   resources:
    #     limits:
    #       memory: 12G

  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - "./server/.env"
    networks:
      - mynetwork
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_started
volumes:
  neo4j_data:
  ollama_models:

networks:
  mynetwork:
