version: "3.9"

services:
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

    ports:
      - "7687:7687" # Bolt protocol (backend connects here)
      - "7474:7474" # Neo4j browser UI
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: >
        sh -c "cypher-shell -u neo4j -p $NEO4J_PASS 'RETURN 1'"
      interval: 10s
      timeout: 5s
      retries: 5
  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    # If we want to limit RAM usage:
    # deploy:
    #   resources:
    #     limits:
    #       memory: 12G

  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - "./server/.env"
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_started
volumes:
  neo4j_data:
