version: "3.9"

services:
  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - mynetwork
    command: >
      sh -c "
        ollama serve &
        sleep 5 &&
        curl -X POST http://localhost:11434/api/generate -H 'Content-Type: application/json' -d '{\"model\":\"llama3\",\"prompt\":\"Ready\"}' || true &&
        wait
      "
    # If we want to limit RAM usage:
    # deploy:
    #   resources:
    #     limits:
    #       memory: 12G
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - "./server/.env"
    networks:
      - mynetwork
    depends_on:
      ollama:
        condition: service_started
volumes:
  neo4j_data:
  ollama_models:

networks:
  mynetwork:
